In [2]:
## numpy详解
import numpy as np

# 创建数组
a = np.array([1, 2, 3])
print(a)        # [1 2 3]

# 数组的维度
print(a.ndim)    # 1

# 数组的形状
print(a.shape)   # (3,)

# 数组的元素个数
print(a.size)    # 3

# 数组的数据类型
print(a.dtype)   # int32

# 数组的元素类型
print(a.dtype.type)   # <class 'numpy.int32'>

# 数组的元素总和
print(a.sum())   # 6

# 数组的元素最大值
print(a.max())   # 3

# 数组的元素最小值
print(a.min())   # 1

# 数组的元素平均值
print(a.mean())  # 2.0

# 数组的元素中位数
print(np.median(a))   # 2.0




[1 2 3]
1
(3,)
3
int64
<class 'numpy.int64'>
6
3
1
2.0
2.0


In [3]:
##数组运算

# 创建数组
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 数组的加法
print(a + b)    # [5 7 9]

# 数组的减法
print(a - b)    # [-3 -3 -3]

# 数组的乘法
print(a * b)    # [ 4 10 18]

# 数组的除法
print(a / b)    # [0.25 0.4  0.5 ]

# 数组的指数运算
print(a ** b)   # [ 1 32 729]

# 数组的矩阵乘法
c = np.array([[1, 2], [3, 4]])
d = np.array([[5, 6], [7, 8]])
print(c @ d)    # [[19 22]
                #  [43 50]]

# 数组的转置
print(a.T)      # [1 2 3]

# 数组的切片
print(a[1:])    # [2 3]

# 数组的布尔运算
print(a > 2)    # [False False  True]

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[[19 22]
 [43 50]]
[1 2 3]
[2 3]
[False False  True]
